export const STARTED = "STARTED";
export const STOPPED = "STOPPED";
export const DEPLOY_SUCCEED = "DEPLOY_SUCCEED";
export const DEPLOY_FAILED = "DEPLOY_FAILED";
export const REMOVED = "REMOVED";
export const STATUS_CHANGED = "STATUS_CHANGED";
export const CLOUD_SDK_NOT_INSTALLED = "CLOUD_SDK_NOT_INSTALLED";